### ISSUE TITLE
Deploy sticker market contracts on Sepolia

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/sticker-market#13]
Status desktop is moving away from using goerli as their test network, since it's being deprecated.
With Sepolia being the new testnet, the sticker market contracts need to be deployed there as well.

We've already discussed this offline with @3esmit. We'll be performing a transaction on Sepolia to deploy the contracts there.

This issue is created to keep track of this task's status.

**Comment by 0x-r4bbit** [comment]
This can now be closed. @3esmit took care of deploying them.
Address can be found in the notes here: https://notes.status.im/vac-sc-pm?view

Still need to be added to this project's readme though. #14

**Comment by 3esmit** [comment]
The new contracts are active and ready to be used.
    ENSUsernames: https://sepolia.etherscan.io/address/0x4ef81bdfcbb003442869b53bf81168c12e1746a8#code
    StickerType: https://sepolia.etherscan.io/address/0x5acbae26c23427aeee0a7f26949f093577a61aab#code
    StickerPack: https://sepolia.etherscan.io/address/0x8cc272396be7583c65bee82cd7b743c69a87287d#code
    StickerMarket: https://sepolia.etherscan.io/address/0xf852198d0385c4b871e0b91804ecd47c6ba97351#code
 ENSUsernames and StickerMarket use SNTV2 (0xE452027cdEF746c7Cd3DB31CB700428b16cD8E51)
