### ISSUE TITLE
Stickermarket empty on Sepolia

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/sticker-market#17]
After deploying the stickermarket on Sepolia (#13) we probably missed to also initialize it with some test data.
This issue came up here: https://github.com/status-im/status-desktop/issues/13672

This needs to be addressed.

**Comment by 3esmit** [comment]
It was deployed fresh, with no data yes.
Now I minted the sticker types in sepolia, the same that are on mainnet, with exact same data, token ids, and etc. I just dont minted any sticker packs (the ones users buy), which seems reasonable for me.

**Comment by 0x-r4bbit** [comment]
@3esmit thank you!

I'm gonna wait for a confirmation from Desktop, then I'll close this.
Thanks again for the quick response.

**Comment by 0x-r4bbit** [comment]
Closing this as done and fixed, as the original desktop issue has been closed as well.

Well done!
